### ISSUE TITLE
Question: Command to purge old users

### ISSUE THREAD

**Issue by LordNex** [Tyrsis/EssentialsPlugin#56]
I was wondering if there is a command to purge old players out of the SBC\SBS file I know it tracks yous so you can delete inactive users grids out but is there a way to remove the players in the database. I remember there was a powershell command out there but i cant seem to find that

Thanks

**Comment by Tyrsis** [comment]
The issue with this is I don't ever touch sandbox files as it's basically unsafe.  Any cleanup I do modifies it in game and relies on the game to save the changes.  That being said I can look for a method of removing users from the internal user list.  I believe that's there, I just have to get some time to figure it out.
