### ISSUE TITLE
TimedCleanup not working.

### ISSUE THREAD

**Issue by ThaHenry** [Tyrsis/EssentialsPlugin#58]
My setup was a CleanupTimedItem with

enabled true
reason cleanup
time : (several testing 5, 10, 15, 30 and 60 minutes ahead. 60 minutes had a server restart in between.
command "hasdisplayname:Large Ship 7910:exact"

There have been 3 ships with displayname "Large Ship 7910" and a search with /admin scan grids "hasdisplayname:Large Ship 7910:exact" returns me all ships

**Comment by Tyrsis** [comment]
This should be fixed in new version.
