### ISSUE TITLE
Number In Server Window

### ISSUE THREAD

**Issue by LordNex** [Tyrsis/EssentialsPlugin#61]
Ever since the last patch of the essentials plugin I've been seeing this in the server output window. It doesn't seem to cause alot of issues but it does cause some lag from the output a loan. It doesn't write these into the log that I can see and I don't see any errors there about this in the logs either. Let me know and I'll post those as well

![sesechain](https://cloud.githubusercontent.com/assets/9270948/5694293/0b542dcc-9913-11e4-9264-bdee229b8e57.png)

**Comment by LordNex** [comment]
http://paste.ee/p/C6OKW
and
http://paste.ee/p/M74mg

**Comment by LordNex** [comment]
Eventually it seemed to stop on the next reboot. But as soon as the cleanup ran the numbers came back

**Comment by demolish50** [comment]
Mine never stopped.

**Comment by Tyrsis** [comment]
Yes it has to do with Timed cleanups.  Sorry.  It was a debug left in.  I will remove it next update probably today or tomorrow.

**Comment by LordNex** [comment]
I haven't had any other issues. If no one else hasn't I'll close this issue in a day or so.

 demolish50?
