### ISSUE TITLE
Waypoints have a limited range on unlimited server

### ISSUE THREAD

**Issue by markam67** [Tyrsis/EssentialsPlugin#64]
Now that we have near limitless server sizes it seems that the Waypoint system is limited to some number of meters maximum that it can be seen. Is it possible to increase this or is that a game engine limitation and needs to be told to Keen?

Thanks,

Markam67

**Comment by Tyrsis** [comment]
The limit is 1 million.  It's hardcoded unfortunately.

**Comment by markam67** [comment]
That sucks I hope Keen address this going forward with the unlimited exploration game mode. 

Thanks for looking into it.

**Comment by McyD** [comment]
Has the limit now been removed that they have implemented their way-point system?
