### ISSUE TITLE
Saving World Please Wait message now appears when server is saving world

### ISSUE THREAD

**Issue by markam67** [Tyrsis/EssentialsPlugin#79]
This popup never happened before but now it happens every time the sever commits a save.Is this an Essentials issues and I have it set up wrong or has Keen changed something with regard to the save mechanism?

thanks,

Markam67

**Comment by McyD** [comment]
This is a Keen issue from the last update.

**Comment by markam67** [comment]
Ok just checking, thanks for the info.
